# -*- coding: utf-8 -*-
"""stream-diabetes.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11g5sfYXA-ml3_gprss7M6ozJgWot_-58
"""

import pickle
import streamlit as st

# membaca model
try:
    diabetes_model = pickle.load(open('diabetes_model.sav', 'rb'))
except FileNotFoundError:
    st.error('Model tidak ditemukan. Pastikan file model ada di direktori yang benar.')
    st.stop()

#judul web
st.title('PREDIKSI PENYAKIT DIABETES')

#membagi kolom
col1, col2 = st.columns(2)

with col1 :
    Pregnancies = st.text_input ('masukkan nilai Pregnancies')

with col2 :
    Glucose = st.text_input ('masukkan nilai Glucose')

with col1 :
    BloodPressure = st.text_input ('masukkan nilai BloodPressure')

with col2 :
    SkinThickness = st.text_input ('masukkan nilai SkinThickness')

with col1 :
    Insulin = st.text_input ('masukkan nilai Insulin')

with col2 :
    BMI = st.text_input ('masukkan nilai BMI')

with col1 :
    DiabetesPedigreeFunction = st.text_input ('masukkan nilai DiabetesPedigreeFunction')

with col2 :
    Age = st.text_input ('masukkan nilai Age')

# kode prediksi
diab_diagnosis = ''

# tombol
if st.button('Test Prediksi Diabetes'):
    try:
        # Konversi input ke tipe data yang benar
        Pregnancies = int(Pregnancies)
        Glucose = int(Glucose)
        BloodPressure = int(BloodPressure)
        SkinThickness = int(SkinThickness)
        Insulin = int(Insulin)
        BMI = float(BMI)
        DiabetesPedigreeFunction = float(DiabetesPedigreeFunction)
        Age = int(Age)

        # Tampilkan input yang dikonversi untuk debugging
        st.write(f'Input yang dikonversi: {Pregnancies}, {Glucose}, {BloodPressure}, {SkinThickness}, {Insulin}, {BMI}, {DiabetesPedigreeFunction}, {Age}')

        # Lakukan prediksi
        diab_prediction = diabetes_model.predict([[Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age]])

        if diab_prediction[0] == 1:
            diab_diagnosis = 'Pasien mengidap diabetes'
        else:
            diab_diagnosis = 'Pasien tidak mengidap diabetes'
        st.success(diab_diagnosis)
    except ValueError:
        st.error('Harap masukkan nilai yang valid untuk semua input.')
    except Exception as e:
        st.error(f'Terjadi kesalahan: {e}')